### ISSUE TITLE
Usefull, but...

### ISSUE THREAD

**Issue by 0o10** [emuzulu/isEven#6]
This is extremely useful. I will be including it in all of my future python projects. 

There is only one problem, it seems that you are missing a few integers. From what I've seen it ranges from 10001 to Infinity. 

(I would like to note that I can't quite confirm this yet, as my tests are still running.)

Otherwise star++ 👍

**Comment by emuzulu** [comment]
I notice your concern, this is a bug our development team is working on fixing and we should deploy a fix in the coming days. We are glad you find our product useful.

**Comment by emuzulu** [comment]
Bug is fixed, added the recursive feature to cover all ranges of integers.
